In [15]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import sklearn.linear_model as lm
import pickle
from sklearn.externals import joblib

In [2]:
df=pd.read_csv("fuelcons.csv")
df.head()

,MODELYEAR,MAKE,MODEL,VEHICLECLASS,ENGINESIZE,CYLINDERS,TRANSMISSION,FUELTYPE,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
0,2014,ACURA,ILX,COMPACT,2.0,4,AS5,Z,9.9,6.7,8.5,33,196
1,2014,ACURA,ILX,COMPACT,2.4,4,M6,Z,11.2,7.7,9.6,29,221
2,2014,ACURA,ILX HYBRID,COMPACT,1.5,4,AV7,Z,6.0,5.8,5.9,48,136
3,2014,ACURA,MDX 4WD,SUV - SMALL,3.5,6,AS6,Z,12.7,9.1,11.1,25,255
4,2014,ACURA,RDX AWD,SUV - SMALL,3.5,6,AS6,Z,12.1,8.7,10.6,27,244

In [3]:
df.describe()

,MODELYEAR,ENGINESIZE,CYLINDERS,FUELCONSUMPTION_CITY,FUELCONSUMPTION_HWY,FUELCONSUMPTION_COMB,FUELCONSUMPTION_COMB_MPG,CO2EMISSIONS
count,1067.0,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000,1067.000000
mean,2014.0,3.346298,5.794752,13.296532,9.474602,11.580881,26.441425,256.228679
std,0.0,1.415895,1.797447,4.101253,2.794510,3.485595,7.468702,63.372304
min,2014.0,1.000000,3.000000,4.600000,4.900000,4.700000,11.000000,108.000000
25%,2014.0,2.000000,4.000000,10.250000,7.500000,9.000000,21.000000,207.000000
50%,2014.0,3.400000,6.000000,12.600000,8.800000,10.900000,26.000000,251.000000
75%,2014.0,4.300000,8.000000,15.550000,10.850000,13.350000,31.000000,294.000000
max,2014.0,8.400000,12.000000,30.200000,20.500000,25.800000,60.000000,488.000000

In [4]:
value=np.random.rand(len(df))<.8
train=df[value]
test=df[~value]

In [5]:
print(train)

      MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4
1          2014  ACURA         ILX         COMPACT         2.4          4
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6
...         ...    ...         ...             ...         ...        ...
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7
1              M6        Z                  11.2                  7.7
2             AV7        Z                   6.0                  5.8
3             AS6        Z                  12.7                  9.1
4             AS6        Z                  12.1                  8.7
...           ...      ...                   ...                  ...
1062          AS6        X                  13.4                  9.8
1063          AS6        X                  13.2                  9.5
1064          AS6        X                  13.4                  9.8
1065          AS6        X                  12.9                  9.3
1066          AS6        X                  14.9                 10.2

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS
0                      8.5                        33           196
1                      9.6                        29           221
2                      5.9                        48           136
3                     11.1                        25           255
4                     10.6                        27           244
...                    ...                       ...           ...
1062                  11.8                        24           271
1063                  11.5                        25           264
1064                  11.8                        24           271
1065                  11.3                        25           260
1066                  12.8                        22           294

[868 rows x 13 columns]

In [6]:
print(test)

      MODELYEAR          MAKE                   MODEL    VEHICLECLASS  \
9          2014         ACURA                     TSX         COMPACT
10         2014         ACURA                     TSX         COMPACT
14         2014  ASTON MARTIN              V8 VANTAGE      TWO-SEATER
24         2014          AUDI              A5 QUATTRO      SUBCOMPACT
32         2014          AUDI     A8 TDI CLEAN DIESEL        MID-SIZE
...         ...           ...                     ...             ...
1034       2014    VOLKSWAGEN                   JETTA         COMPACT
1041       2014    VOLKSWAGEN  JETTA TDI CLEAN DIESEL         COMPACT
1044       2014    VOLKSWAGEN                  PASSAT        MID-SIZE
1050       2014    VOLKSWAGEN                  ROUTAN         MINIVAN
1054       2014    VOLKSWAGEN                 TOUAREG  SUV - STANDARD

      ENGINESIZE  CYLINDERS TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  \
9            2.4          4          AS5        Z                  10.6
10           2.4          4           M6        Z                  11.2
14           4.7          8          AM7        Z                  17.4
24           2.0          4           M6        Z                  10.8
32           3.0          6          AS8        D                  10.0
...          ...        ...          ...      ...                   ...
1034         1.8          4           A6        X                   9.5
1041         2.0          4           M6        D                   7.9
1044         1.8          4           M5        X                  10.0
1050         3.6          6           A6        X                  14.2
1054         3.6          6          AS8        Z                  13.8

      FUELCONSUMPTION_HWY  FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  \
9                     7.5                   9.2                        31
10                    8.1                   9.8                        29
14                   11.3                  14.7                        19
24                    7.5                   9.3                        30
32                    6.4                   8.4                        34
...                   ...                   ...                       ...
1034                  6.7                   8.2                        34
1041                  5.6                   6.9                        41
1044                  6.9                   8.6                        33
1050                  9.5                  12.1                        23
1054                 10.3                  12.2                        23

      CO2EMISSIONS
9              212
10             225
14             338
24             214
32             227
...            ...
1034           189
1041           186
1044           198
1050           278
1054           281

[199 rows x 13 columns]

In [7]:
regr=lm.LinearRegression()
train_x=np.asanyarray(train[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_CITY"]])
train_y=np.asanyarray(train[["CO2EMISSIONS"]])
regr.fit(train_x,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [8]:
print(regr.coef_)

[[12.0736602   5.93083187  8.49033973]]

In [9]:
print(regr.intercept_)

[68.81076313]

In [10]:
#Saving the model

joblib.dump(regr,"fuelmodel.pkl")

['fuelmodel.pkl']

In [11]:
test_x=np.asanyarray(test[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_CITY"]])
test_y=np.asanyarray(test[["CO2EMISSIONS"]])
prediction=regr.predict(test_x)
print(prediction)

[[211.50847626]
 [216.6026801 ]
 [320.73553239]
 [208.37708012]
 [225.52013228]
 [216.86741986]
 [264.57569505]
 [285.1148831 ]
 [387.69288349]
 [201.58480834]
 [206.67901218]
 [241.65177777]
 [204.98094423]
 [291.64241513]
 [296.73661897]
 [296.73661897]
 [316.26440035]
 [316.26440035]
 [306.92502665]
 [250.14211751]
 [190.09544235]
 [203.01813652]
 [214.32031794]
 [214.32031794]
 [212.62224999]
 [219.41452178]
 [260.78244952]
 [217.71645383]
 [276.06506104]
 [269.27278925]
 [268.42375528]
 [317.62017335]
 [307.43176567]
 [186.69930646]
 [203.41524616]
 [190.54736669]
 [335.62103426]
 [254.83921171]
 [316.77991416]
 [345.80944194]
 [329.50664898]
 [306.75387917]
 [189.83070259]
 [189.83070259]
 [362.79012141]
 [362.79012141]
 [253.14114376]
 [216.6026801 ]
 [259.93341555]
 [259.93341555]
 [207.26330639]
 [208.11234036]
 [268.42375528]
 [308.32835202]
 [194.34061222]
 [253.63184569]
 [389.46850662]
 [272.3105931 ]
 [184.01983466]
 [184.86886863]
 [272.3105931 ]
 [192.24543463]
 [216.01838588]
 [193.94350258]
 [209.2261141 ]
 [307.37695098]
 [321.281049  ]
 [223.75328393]
 [381.46886882]
 [383.16693676]
 [374.63781944]
 [443.40957127]
 [355.05522336]
 [270.08304563]
 [316.77991416]
 [304.20677725]
 [329.50664898]
 [276.87531742]
 [326.11928786]
 [273.51795912]
 [316.09325288]
 [409.31584246]
 [316.09325288]
 [362.79012141]
 [240.04730211]
 [186.4345667 ]
 [211.50847626]
 [175.17116288]
 [181.11440069]
 [259.5750835 ]
 [186.56693658]
 [185.71790261]
 [260.65007964]
 [219.99881599]
 [194.20824234]
 [261.14078156]
 [264.53691746]
 [331.60182656]
 [244.19887969]
 [265.42472902]
 [309.9240529 ]
 [357.4699554 ]
 [351.52671759]
 [310.77308687]
 [214.05557818]
 [249.16071365]
 [208.96137434]
 [220.84784996]
 [331.96015861]
 [235.70853996]
 [350.60012843]
 [203.28287628]
 [220.84784996]
 [193.22683849]
 [206.09471796]
 [203.54761604]
 [224.50872562]
 [223.39495188]
 [412.03928279]
 [329.45183428]
 [322.6595625 ]
 [388.88421241]
 [261.17955916]
 [261.17955916]
 [329.45183428]
 [160.9635475 ]
 [171.96221156]
 [249.38667582]
 [260.29174759]
 [269.66989889]
 [269.66989889]
 [181.96343467]
 [216.96101214]
 [210.92418204]
 [206.81138206]
 [249.38667582]
 [204.13191026]
 [310.86667916]
 [310.86667916]
 [190.05666476]
 [248.53764185]
 [228.16082649]
 [314.26281505]
 [297.78161229]
 [240.8027438 ]
 [286.77417346]
 [184.86886863]
 [184.86886863]
 [184.86886863]
 [190.81210645]
 [189.1140385 ]
 [190.81210645]
 [189.1140385 ]
 [237.24423521]
 [198.18867245]
 [199.88674039]
 [261.98981554]
 [263.68788348]
 [346.03540411]
 [277.49838922]
 [199.98033268]
 [203.37646857]
 [335.84699643]
 [289.38486485]
 [281.74355909]
 [245.63220788]
 [258.10297772]
 [259.80104567]
 [243.93413993]
 [246.48124185]
 [227.84127204]
 [257.38631363]
 [254.38728737]
 [209.2261141 ]
 [209.31970638]
 [399.34462217]
 [204.22550254]
 [218.65908009]
 [197.33963847]
 [185.45316285]
 [187.28360067]
 [179.64229491]
 [154.17127572]
 [346.39373615]
 [256.17894761]
 [278.3474232 ]
 [221.9228461 ]
 [253.63184569]
 [176.86923083]
 [194.92490643]
 [198.32104233]
 [197.47200835]
 [223.74087799]
 [215.16935191]
 [194.92490643]
 [183.7550949 ]
 [199.1700763 ]
 [268.42375528]
 [265.02761938]]

In [13]:
predict_df=pd.read_csv("check1.csv")
predict_df.head()

   ENGINESIZE  CYLINDERS  FUELCONSUMPTION_CITY  CO2EMISSIONS
0         3.2         10                   7.2             0

In [14]:
predict_x=np.asanyarray(predict_df[["ENGINESIZE","CYLINDERS","FUELCONSUMPTION_CITY"]])
prediction=regr.predict(predict_x)
print(prediction)

[[227.88524057]]